---
- name: Raspberry Pi Initial Setup
  hosts: raspberry

  tasks:
  - name: System Upgrade
    apt:
      upgrade: full
      update_cache: yes
      autoremove: yes
    become: yes
  - name: Install Vim 
    apt:
      name: vim
    become: yes
  - name: Configure Tailscale
    include_role:
      name: artis3n.tailscale
    vars:
      tailscale_authkey: "{{ tailscale_key }}"
    no_log: True
